name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: profile
          stats: true
          top_languages: true
